# Generated by Django 4.2.2 on 2023-07-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheWebsiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentsNumber', models.IntegerField()),
                ('CoursesNumber', models.IntegerField()),
                ('EventsNumber', models.IntegerField()),
                ('TrainersNumber', models.IntegerField()),
            ],
        ),
    ]
