# Generated by Django 4.2.2 on 2023-07-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheWebsiteAboutText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_txt', models.TextField(blank=True)),
            ],
        ),
    ]
