# Generated by Django 4.2.2 on 2023-07-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_thewebsiteabouttext'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheWebsiteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WebsiteImg', models.ImageField(upload_to='static\x07ssets\\img')),
            ],
        ),
    ]
