# Generated by Django 4.2.2 on 2023-07-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_thewebsiteimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thewebsiteimages',
            name='WebsiteImg',
            field=models.ImageField(upload_to='static/assets/img'),
        ),
    ]
