# Generated by Django 4.2.2 on 2023-07-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_thewebsiteimages_websiteimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheWebsiteTrainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('Title', models.CharField(max_length=200)),
                ('Desc', models.CharField(max_length=500)),
                ('Social', models.URLField(blank=True)),
            ],
        ),
    ]
