# Generated by Django 4.2.2 on 2023-07-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_thewebsitetrainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='thewebsitetrainers',
            name='Image',
            field=models.ImageField(blank=True, upload_to='static/assets/img/trainer'),
        ),
    ]
