# Generated by Django 4.2.2 on 2023-07-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_thewebsitetrainers_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheWebsiteCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Desc', models.CharField(max_length=500)),
                ('Subjects', models.CharField(max_length=500)),
                ('Image', models.ImageField(blank=True, upload_to='static/assets/img/trainer/subjects')),
                ('BigImage', models.ImageField(blank=True, upload_to='static/assets/img/trainer/subjects')),
                ('LongDescription', models.TextField(blank=True)),
            ],
        ),
    ]
