# Generated by Django 4.2.2 on 2023-07-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_thewebsitecourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='thewebsitecourses',
            name='smalltitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
