# Generated by Django 4.2.2 on 2023-07-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_thewebsitecourses_smalltitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheWebsitePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100)),
                ('Money', models.CharField(blank=True, max_length=100)),
                ('Freq', models.CharField(blank=True, max_length=100)),
                ('Desc', models.CharField(blank=True, max_length=500)),
                ('Crossed', models.CharField(blank=True, max_length=500)),
                ('CourseTitle', models.CharField(max_length=200)),
            ],
        ),
    ]
