# Generated by Django 4.2.2 on 2023-08-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_thewebsitepricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheWebsiteTestimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=70)),
                ('Image', models.ImageField(blank=True, upload_to='static/assets/img/testimony')),
                ('Title', models.CharField(blank=True, max_length=200)),
                ('Saying', models.TextField(blank=True)),
                ('Social', models.URLField(blank=True)),
            ],
        ),
    ]
